export interface ProductItem {
  _id?: string
  id?: string
  name: string
  slug: string
  description: string
  price: number
  originalPrice?: number
  stock: number
  sport: 'football' | 'basketball' | 'tennis' | 'running' | 'fitness' | 'badminton' | 'other'
  category: 'clothes' | 'shoes' | 'equipment' | 'accessories'
  brand: string
  images: string[]
  sizes: string[]
  colors: string[]
  isFeatured: boolean
  isNewArrival: boolean
}

export const INITIAL_PRODUCTS: ProductItem[] = [
  {
    id: '1',
    name: 'Nike Mercurial Superfly 9 Elite FG',
    slug: 'nike-mercurial-superfly-9-elite-fg',
    description: 'Pro football boots built for explosive speed on firm ground pitches. Features Zoom Air unit in the plate for responsive cushioning.',
    price: 279.99,
    originalPrice: 299.99,
    stock: 24,
    sport: 'football',
    category: 'shoes',
    brand: 'Nike',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop'],
    sizes: ['US 8', 'US 9', 'US 10', 'US 11'],
    colors: ['Volt Yellow', 'Electric Blue', 'Phantom Black'],
    isFeatured: true,
    isNewArrival: true,
  },
  {
    id: '2',
    name: 'Adidas Real Madrid Home Jersey 2024/25',
    slug: 'adidas-real-madrid-home-jersey-24-25',
    description: 'Official matchday football jersey engineered with HEAT.RDY technology for maximum ventilation and light feel.',
    price: 119.99,
    originalPrice: 139.99,
    stock: 45,
    sport: 'football',
    category: 'clothes',
    brand: 'Adidas',
    images: ['https://images.unsplash.com/photo-1577223625816-7546f13df25d?q=80&w=1000&auto=format&fit=crop'],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    colors: ['Pure White/Gold'],
    isFeatured: true,
    isNewArrival: false,
  },
  {
    id: '3',
    name: 'Air Jordan 38 Low Basketball Shoes',
    slug: 'air-jordan-38-low-basketball-shoes',
    description: 'Next-gen basketball sneakers with X-Plate stability technology and Formula 23 foam for high-flying court performance.',
    price: 189.99,
    stock: 18,
    sport: 'basketball',
    category: 'shoes',
    brand: 'Jordan',
    images: ['https://images.unsplash.com/photo-1579338559194-a162d19bf842?q=80&w=1000&auto=format&fit=crop'],
    sizes: ['US 9', 'US 10', 'US 10.5', 'US 11.5', 'US 12'],
    colors: ['Black/University Red', 'White/Infrared'],
    isFeatured: true,
    isNewArrival: true,
  },
  {
    id: '4',
    name: 'Wilson Pro Staff 97 v14 Tennis Racket',
    slug: 'wilson-pro-staff-97-v14-tennis-racket',
    description: 'Iconic tennis racket offering legendary precision, Braid 45 construction, and sleek velvet metallic finish.',
    price: 259.00,
    originalPrice: 279.00,
    stock: 12,
    sport: 'tennis',
    category: 'equipment',
    brand: 'Wilson',
    images: ['https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?q=80&w=1000&auto=format&fit=crop'],
    sizes: ['Grip 2 (4 1/4")', 'Grip 3 (4 3/8")'],
    colors: ['Bronze Velvet'],
    isFeatured: false,
    isNewArrival: true,
  },
  {
    id: '5',
    name: 'Asics Gel-Resolution 9 Tennis Shoes',
    slug: 'asics-gel-resolution-9-tennis-shoes',
    description: 'High-stability tennis shoes designed for baseline domination. DYNAWALL technology enhances lateral movement recovery.',
    price: 149.95,
    stock: 30,
    sport: 'tennis',
    category: 'shoes',
    brand: 'Asics',
    images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=1000&auto=format&fit=crop'],
    sizes: ['US 8.5', 'US 9.5', 'US 10.5', 'US 11'],
    colors: ['White/Restful Teal', 'Black/Neon Sun'],
    isFeatured: false,
    isNewArrival: false,
  },
  {
    id: '6',
    name: 'Puma Dri-FIT Pro Basketball Shorts',
    slug: 'puma-dri-fit-pro-basketball-shorts',
    description: 'Lightweight mesh basketball shorts featuring elastic drawstring waistband, deep side pockets, and moisture management.',
    price: 49.99,
    originalPrice: 65.00,
    stock: 60,
    sport: 'basketball',
    category: 'clothes',
    brand: 'Puma',
    images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Jet Black', 'Puma Navy'],
    isFeatured: false,
    isNewArrival: true,
  },
  {
    id: '7',
    name: 'Nike ZoomX Vaporfly NEXT% 3 Running Shoes',
    slug: 'nike-zoomx-vaporfly-next-3-running-shoes',
    description: 'Marathon racing shoe with carbon-fiber Flyplate and full-length ZoomX foam for unprecedented energy return.',
    price: 259.99,
    stock: 15,
    sport: 'running',
    category: 'shoes',
    brand: 'Nike',
    images: ['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?q=80&w=1000&auto=format&fit=crop'],
    sizes: ['US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    colors: ['Proto White/Orange', 'Volt Lime'],
    isFeatured: true,
    isNewArrival: true,
  },
  {
    id: '8',
    name: 'Under Armour Tech 2.0 Short Sleeve Shirt',
    slug: 'under-armour-tech-2-0-short-sleeve-shirt',
    description: 'Ultra-soft training shirt built for high-intensity fitness sessions with anti-odor technology and quick-dry fabric.',
    price: 29.99,
    originalPrice: 35.00,
    stock: 80,
    sport: 'fitness',
    category: 'clothes',
    brand: 'Under Armour',
    images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop'],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    colors: ['Charcoal Gray', 'Royals Blue', 'Red'],
    isFeatured: false,
    isNewArrival: false,
  },
]
